---
ssh_permit_root_login: "no"
ssh_password_authentication: "no"
ssh_max_auth_tries: 3

linux_allowed_ports:
  - "22"

unused_services:
  - telnet
  - vsftpd

audit_rules:
  - "-w /etc/passwd -p wa -k passwd_changes"
  - "-w /etc/shadow -p wa -k shadow_changes"
  - "-w /etc/ssh/sshd_config -p wa -k ssh_config"