---
- name: Install auditd
  ansible.builtin.apt:
    name: auditd
    state: present

- name: Try to enable auditd
  ansible.builtin.systemd:
    name: auditd
    state: started
    enabled: true
  ignore_errors: true

- name: Add audit rules
  ansible.builtin.lineinfile:
    path: /etc/audit/rules.d/hardening.rules
    line: "{{ item }}"
    create: true
    mode: '0644'
  loop: "{{ linux_hardening_audit_rules }}"