---
- name: Install fail2ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: true

- name: Configure fail2ban jail.local
  ansible.builtin.copy:
    dest: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = {{ linux_hardening_fail2ban_bantime }}
      findtime = {{ linux_hardening_fail2ban_findtime }}
      maxretry = {{ linux_hardening_fail2ban_maxretry }}

      [sshd]
      enabled = true
      port = ssh
      logpath = %(sshd_log)s
    mode: '0644'

- name: Try to enable and start fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
    state: started
  ignore_errors: true