---
- name: Stop vulnerable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop:
    - vsftpd

- name: Remove telnet package
  ansible.builtin.apt:
    name: telnet
    state: absent