---
- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: "PermitRootLogin {{ linux_hardening_ssh_permit_root_login }}"
  notify: Restart ssh

- name: Disable password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: "PasswordAuthentication {{ linux_hardening_ssh_password_authentication }}"
  notify: Restart ssh

- name: Reduce MaxAuthTries
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?MaxAuthTries'
    line: "MaxAuthTries {{ linux_hardening_ssh_max_auth_tries }}"
  notify: Restart ssh